[book]
authors = ["liwei"]
language = "en"
multilingual = false
src = "src"
title = "LangChain 中文开发文档"
[output.html]
additional-css = ["theme/style.css","assets/custom.css"]
additional-js = ["assets/custom.js", "assets/bigPicture.js"]
git-repository-url = "https://github.com/liweiv/langchain-zh_CN"
[output.html.playground]
editable = true
copy-js = true
[output.html.fold]
enable = true
level = 0
